name: Release

on:
  push:
    tags:
      - 'v*'

  # Enables the manual "Run Workflow" button
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual deploy'
        required: false
        default: 'Manual override'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc

    - name: Build Release
      run: cargo build --release --verbose

    - name: List Release Directory
      run: dir target/release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: air-windows
        path: target/release/air.exe

    - name: Generate Tag Name
      id: tag
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "tag_name=manual-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
        else
          echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
      with:
        files: target/release/air.exe
        tag_name: ${{ steps.tag.outputs.tag_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
